### ISSUE TITLE
Need version of metro-wsit / metro.webservices-api-osgi supporting jakarta.xml.bind 4

### ISSUE THREAD

**Issue by arjantijms** [eclipse-ee4j/metro-wsit#138]
Integrating JAX-B 4.0.0* in GlassFish leads to the following error being printed:

```
Unable to resolve
    org.glassfish.main.webservices.connector [207]
    missing requirement
        &(package = jakarta.xml.ws) (version >= 3.0.0) (!(version >= 4.0.0))
        caused by:
            Unable to resolve
                org.glassfish.metro.webservices-api-osgi [236]
                missing requirement
                    &(package = jakarta.xml.bind) (version >= 3.0.0) (!(version >= 4.0.0)))]
```

*
```
<!-- Jakarta XML Binding -->
<jakarta.jaxb-api.version>4.0.0-RC2</jakarta.jaxb-api.version>
<jakarta.jaxb-impl.version>4.0.0-M1</jakarta.jaxb-impl.version>
```

I think a new version of "org.glassfish.metro.webservices-api-osgi" is needed?

**Comment by lukasj** [comment]
right, there are more things this depends on (some ~10-15 other projects which needs to be updated...), so it will take time

**Comment by lukasj** [comment]
try 4.0.0-M1 Note that apart from updated dependencies (APIs as well as impls), there is additional change which has impact on GF integration - Apache Santuario has been moved away from the webservices-osgi artifact, so to get it, GF needs `org.apache.santuario:xmlsec:2.1.7`; to get its dependencies, GF needs new `org.glassfish.metro:webservices-extra-xmlsec` artifact which repackages santuario deps including jaxb2; see #144

**Comment by lukasj** [comment]
let me know if you find any issues, I haven't had a chance to test this version on the GF side yet.

**Comment by arjantijms** [comment]
@lukasj 

One issue is a compile error now.

After M1 it decided to hate this fragment in metro-glue, MetroContainer:

```java
final WSATRuntimeConfig.RecoveryEventListener metroListener = WSATRuntimeConfig.getInstance().new WSATRecoveryEventListener();
```

/glassfish/appserver/webservices/metro-glue/src/main/java/org/glassfish/webservices/metroglue/MetroContainer.java:[280,100] qualified new of static class

**Comment by arjantijms** [comment]
I'll try to turn it into something like

```java
WSATRuntimeConfig.getInstance(); // Side effect needed?

final WSATRuntimeConfig.RecoveryEventListener metroListener = new WSATRuntimeConfig.WSATRecoveryEventListener();
```

**Comment by arjantijms** [comment]
@lukasj With 4.0.0-M1, GF starts, but upon deploying a war the following is logged:

```
[#|2021-12-16T23:38:40.025+0100|SEVERE|glassfish 7.0|jakarta.enterprise.web.core|_ThreadID=50;_ThreadName=RunLevelControllerThread-1639694318799;_TimeMillis=1639694320025;_LevelValue=1000;|
  java.util.ServiceConfigurationError: jakarta.servlet.ServletContainerInitializer: Provider com.sun.xml.ws.transport.http.servlet.WSServletContainerInitializer not found
	at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:593)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.nextProviderClass(ServiceLoader.java:1219)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(ServiceLoader.java:1228)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(ServiceLoader.java:1273)
	at java.base/java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1309)
	at java.base/java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1393)
	at org.apache.catalina.core.StandardContext.callServletContainerInitializers(StandardContext.java:5657)
	at com.sun.enterprise.web.WebModule.callServletContainerInitializers(WebModule.java:594)
```

This is almost always due to Felix not finding all dependencies or finding them in the right versions, but unfortunately Felix swallows the real cause. I'll try debugging to dig it up.

**Comment by arjantijms** [comment]
Upon doing a request, the following error is logged:

```
3. java.lang.IllegalStateException: Unable to resolve
    org.glassfish.main.security.webservices.security [258]
    missing requirement
        &(package = com.sun.xml.ws.api.message) (version >= 4.0.0) (!(version >= 5.0.0))
        caused by:
            Unable to resolve
                org.glassfish.metro.webservices-osgi [26]
                missing requirement
                    &(package = org.apache.jcp.xml.dsig.internal.dom) (version >= 2.1.0) (!(version >= 3.0.0)))]
```

It happens specifically when the `AuthConfigFactory` from Jakarta Authentication is obtained, as per the following code:

```java
/**
 * This is based Helper class for 196 Configuration. This class implements RegistrationListener.
 */
public abstract class ConfigHelper /* implements RegistrationListener */ {
    private static final String DEFAULT_HANDLER_CLASS = "com.sun.enterprise.security.jmac.callback.ContainerCallbackHandler";

    //    private static String handlerClassName = null;
    protected static final AuthConfigFactory factory = AuthConfigFactory.getFactory();
```

**Comment by arjantijms** [comment]
> GF needs org.apache.santuario:xmlsec:2.1.7; to get its dependencies, GF needs new org.glassfish.metro:webservices-extra-xmlsec artifact which repackages santuario deps including jaxb2; 

I didn't interpret this correctly, I think you're saying here that I need santuario separately next to webservices-extra-xmlsec. I read it first as only needing webservices-extra-xmlsec.

**Comment by lukasj** [comment]
wrt WSATRecoveryEventListener - that should not have been made static, I've reverted that piece of change (see https://github.com/eclipse-ee4j/metro-wsit/pull/146)

wrt xmlsec:
with metro < 4.0.0, use `org.glassfish.metro:webservices-osgi`
with metro 4.0.0+, use `org.glassfish.metro:webservices-osgi` + `org.glassfish.metro:webservices-extra-xmlsec` + `org.apache.santuario:xmlsec:2.1.7` (or whatever version of santuario comes with metro)

the `org.glassfish.metro:webservices-extra-xmlsec` artifact contains dependencies of `xmlsec` - jaxb2+commons.codec+slf4j-api

**Comment by arjantijms** [comment]
@lukasj thanks. I'm a bit further, but GF still crashes quickly. The issue is now with the versions that metro references for various Jakarta artefacts. From `META-INF/MANIFEST.MF`

```
      jakarta.security.auth.message.callback;resolution:=optional;version="[2.0,3)"
      jakarta.security.auth.message.config;resolution:=optional;version="[2.0,3)"
      jakarta.security.auth.message.module;resolution:=optional;version="[2.0,3)"
      jakarta.security.auth.message;resolution:=optional;version="[2.0,3)"
      jakarta.servlet.annotation;resolution:=optional;version="[5.0,6)"
      jakarta.servlet.http;resolution:=optional;version="[5.0,6)"
      jakarta.servlet;resolution:=optional;version="[5.0,6)"
```

This causes class not found exceptions for the metro bundle, since GF bundles, Jakarta Authentication 3.0 and Servlet 6.0 among others.

I'll create a new issue for that.
