### ISSUE TITLE
improve shared targets/properties

### ISSUE THREAD

**Issue by Tomas-Kraus** [eclipse-ee4j/metro-wsit#196]
Shared targets should be moved out of properties.xml into a dedicated build
file. properties.xml is not intended to hold anything else but properties.

Shared properties that hold a filename should be defined against a root.
Currently they are defined as relative paths and are not usable from different
file roots.
#### Environment
Operating System: All
Platform: Macintosh
#### Affected Versions
[current]

Source: [https://github.com/javaee/metro-wsit/issues/272](https://github.com/javaee/metro-wsit/issues/272)
Author: glassfishrobot

**Comment by lukasj** [comment]
obsolete
