### ISSUE TITLE
Java 11 support

### ISSUE THREAD

**Issue by sharangthorat** [eclipse-ee4j/metro-wsit#37]
Hi,
What is plan for Java 11 support? 
Is latest release fully supported with Java 11 ?
Is there any timeline and release by which one can expect Java 11 support ?

Below is jdepscan report with release I am using

**Webservices-rt-2.4.2.jar**

JDK Internal API Suggested Replacement

---------------- ---------------------

com.sun.org.apache.xml.internal.resolver.Catalog Use javax.xml.catalog @since 9

com.sun.org.apache.xml.internal.resolver.CatalogManager Use javax.xml.catalog @since 9

com.sun.org.apache.xml.internal.resolver.tools.CatalogResolver Use javax.xml.catalog @since 9

sun.misc.BASE64Encoder Use java.util.Base64 @since 1.8 sun.misc.HexDumpEncoder Removed. See http://openjdk.java.net/jeps/260

sun.security.action.GetBooleanAction Use java.security.PrivilegedAction @since 1.1

sun.security.krb5.Checksum Use com.sun.security.jgss

sun.security.krb5.Config Use com.sun.security.jgss

sun.security.krb5.Confounder Use com.sun.security.jgss

sun.security.krb5.Credentials Use com.sun.security.jgss

sun.security.krb5.EncryptionKey Use com.sun.security.jgss

sun.security.krb5.KrbApRep Use com.sun.security.jgss

sun.security.krb5.KrbApReq Use com.sun.security.jgss

sun.security.krb5.KrbCred Use com.sun.security.jgss

sun.security.krb5.KrbException Use com.sun.security.jgss

sun.security.krb5.PrincipalName Use com.sun.security.jgss

sun.security.krb5.ServiceName Use com.sun.security.jgss

sun.security.krb5.internal.crypto.Aes128 Use com.sun.security.jgss

sun.security.krb5.internal.crypto.Aes256 Use com.sun.security.jgss

sun.security.krb5.internal.crypto.ArcFourHmac Use com.sun.security.jgss

sun.security.krb5.internal.crypto.Des3 Use com.sun.security.jgss

**Webservices-tools-2.4.2.jar**

webservices-tools :) jdeps -jdkinternals webservices-tools-2.4.2.jar

webservices-tools-2.4.2.jar -> JDK removed internal API

com.sun.tools.xjc.CatalogUtil -> com.sun.org.apache.xml.internal.resolver.Catalog JDK internal API (JDK removed internal API)

com.sun.tools.xjc.CatalogUtil -> com.sun.org.apache.xml.internal.resolver.CatalogManager JDK internal API (JDK removed internal API)

com.sun.tools.xjc.CatalogUtil -> com.sun.org.apache.xml.internal.resolver.tools.CatalogResolver JDK internal API (JDK removed internal API)

Warning: JDK internal APIs are unsupported and private to JDK implementation that are

subject to be removed or changed incompatibly and could break your application.

Please modify your code to eliminate dependence on any JDK internal APIs.

For the most recent update on JDK internal API replacements, please check: https://wiki.openjdk.java.net/display/JDK8/Java+Dependency+Analysis+Tool

JDK Internal API Suggested Replacement

---------------- ---------------------

com.sun.org.apache.xml.internal.resolver.Catalog Use javax.xml.catalog @since 9

com.sun.org.apache.xml.internal.resolver.CatalogManager Use javax.xml.catalog @since 9

com.sun.org.apache.xml.internal.resolver.tools.CatalogResolver Use javax.xml.catalog @since 9

**Comment by lukasj** [comment]
there should be no problems on jdk11 these days
