### ISSUE TITLE
setup Jenkins job

### ISSUE THREAD

**Issue by Tomas-Kraus** [eclipse-ee4j/metro-wsit#397]
1. Add support for glassfish 5.
2. change 8080 to 7998 for port conflict. 
3. Disable devtest due to build issue and webservice folder has not been moved to tests/
4. Only generate patch for published metro.

@Xiaojwu  @zhengjl  @gaoyan-gao @HOHOWU @lukasj 

Source: [https://github.com/javaee/metro-wsit/pull/1699](https://github.com/javaee/metro-wsit/pull/1699)
Author: yuHe1

**Comment by lukasj** [comment]
this is obsolete
