### ISSUE TITLE
Need support information for Jakarta EE specification

### ISSUE THREAD

**Issue by rarathore** [eclipse-ee4j/metro-wsit#433]
Hi Team,

is there any plan to support Jakarta EE specification. if yes form Which release it is supported and any tentative release date.

**Comment by arjantijms** [comment]
Jakarta EE 10 is supported. It was released on 22 September, 2022.

**Comment by rarathore** [comment]
@arjantijms : which release it is supported? is it supported in 2.4.x series?

**Comment by arjantijms** [comment]
GlassFish 7 implements Jakarta EE 10, and it contains Metro/WebServices/WSIT 4.0.2.

**Comment by rarathore** [comment]
@arjantijms : is there any plan to backport in 2.4.x or 3.x.x series?

**Comment by lukasj** [comment]
Have you had a chance to check [the releases](https://github.com/eclipse-ee4j/metro-wsit/releases), [project description page](https://projects.eclipse.org/projects/ee4j.metro) or [project home page](https://eclipse-ee4j.github.io/metro-wsit/)? While I have to admit they are not 100% up-to date, they should give one a good overview about which specs are implemented by Eclipse Metro and its particular parts.

Generally - version 2.4.x is for Jakarta EE 8, 3.0.x for Jakarta EE 9, 4.0.x for Jakarta EE 10

**Comment by arjantijms** [comment]
> is there any plan to backport in 2.4.x or 3.x.x series?

I don't think 4.0.2 is going to be backported to 2.x or 3.x. That would mean 2.x would become 4.x too, but we already have 4.x. But Lukas can probably confirm this.
