### ISSUE TITLE
2.4.3 release should not contain reference to 2.4.4-SNAPSHOT in pom(s)

### ISSUE THREAD

**Issue by ghost** [eclipse-ee4j/metro-wsit#46]
2.4.3 release should not contain reference to 2.4.4-SNAPSHOT in pom(s)

**Comment by lukasj** [comment]
can you point to exact location where this is, please? Thx!

**Comment by ghost** [comment]
This commit within branch RELEASE-2.4.3 :
https://github.com/eclipse-ee4j/metro-wsit/commit/69b426e716e3bf9668d05958a499fd0c41e193d8

I see I can use TAG-2.4.3 where version in poms is correct.

**Comment by lukasj** [comment]
should you need final/released state, then TAG is what you are looking for; branches are living (usually) so can be few commits ahead of tag...
