### ISSUE TITLE
Integrate to GlassFish

### ISSUE THREAD

**Issue by m0mus** [eclipse-ee4j/metro-wsit#6]
- [x] Integrate to Eclipse GlassFish
- [ ] Pass all CTS/TCK tests

#1 must be finished before starting working on this task.

JAXB API and impl, SAAJ API and impl, JAX-WS API and impl + various satellite projects are integrated to GlassFish as part of Metro.

**Comment by lukasj** [comment]
see https://github.com/eclipse-ee4j/glassfish/pull/22654
